gracefully handle distributions without source info
WanzenBug/pylint-import-requirements pull request #25
Opened 2020-07-30 18:02 UTC by WanzenBug

Some distributions do not provide source information.
Notably those installed via apt, dnf and probably more
system package managers. Without the source information
we are not able to resolve an import to a distribution.

Instead of failing on such distributions from the start,
we introduce a new warning type. imports which cannot be
resolved to a distribution are labeled with this warning,
which also provides clues on which distributions could not
be resolved.

As an additional benefit, separating these warnings makes it
also easier to surpress them by the user.

Fixes #24

2020-07-30 18:41 UTC, WanzenBug commented
@fphammerle Any idea how to handle a test in this case?

2020-07-30 20:38 UTC, fphammerle commented
> @fphammerle Any idea how to handle a test in this case?

Horribly hacky approach, but theoretically we could....

1. setup a virtualenv in a pytest-generated temporary dir
2. install `some_small_package`
3. temporarily prepend the virtualenv to `sys.path`
4. `os.unlink(some_small_package.dist-info/RECORD)`
5. run linter over `setup.py` including `install_requires=['some_small_packages', ...]`

```sh
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install importlib_metadata==1.7.0
Collecting importlib_metadata
  Downloading importlib_metadata-1.7.0-py2.py3-none-any.whl (31 kB)
Collecting zipp>=0.5
  Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Installing collected packages: zipp, importlib-metadata
Successfully installed importlib-metadata-1.7.0 zipp-3.1.0
(venv) $ python3 -c 'import importlib_metadata; print(importlib_metadata.PathDistribution.from_name("zipp").files is None)'
False
(venv) $ rm $VIRTUAL_ENV/lib/python3.8/site-packages/zipp-3.1.0.dist-info/RECORD
(venv) $ python3 -c 'import importlib_metadata; print(importlib_metadata.PathDistribution.from_name("zipp").files is None)'
True
```

2020-07-30 20:39 UTC, fphammerle commented
Thanks for preparing the PR! :+1:

2020-07-30 20:52 UTC, fphammerle commented
In case you prefer a mock, maybe:
```python
with unittest.mock.patch.object(importlib_metadata.PathDistribution, 'files', new_callable=unittest.mock.PropertyMock) as files_property_mock: 
    files_property_mock.return_value = None
    print(importlib_metadata.PathDistribution.from_name("zipp").files) 
```

2020-07-31 11:35 UTC, fphammerle commented
for reference: `importlib_metadata.Distribution.files`'s definition https://gitlab.com/python-devs/importlib_metadata/-/blob/v1.7.0/importlib_metadata/__init__.py#L292

2020-07-31 21:01 UTC, WanzenBug commented
I made a "poor man's virtualenv" by just creating a mock `site-package` path that can be added to `sys.path`. I added 2 packages in the "wrong" metadata format (i.e. with source file information).

2020-08-03 16:11 UTC, fphammerle requested changes
Awesome, thanks a lot!
Nice test approach :+1:

I'm so glad we added tests from the start

This plugin turned out much more complicated then I originally expected

Please add a line to `CHANGELOG.md`

2020-08-03 16:11 UTC, fphammerle commented on pylint_import_requirements/__init__.py
> +
cosmetics: 
```
else:
      resolved_filepaths =
      # ...
      self.known_files.update(distribution_file_info)
```
instead of
```
distribution_files = []
```

would that be easier to read?

2020-08-03 19:47 UTC, WanzenBug commented on pylint_import_requirements/__init__.py
> +
I'm not a fan of big `if: else:` branches. So instead I used the ``dist.files or []` shortcut and moved the check for empty files at a later stage (doesn't really change anything, just felt "better" there)

2020-08-03 19:47 UTC, WanzenBug commented
@fphammerle changelog added + see discussion

2020-08-03 20:05 UTC, fphammerle approved these changes

2020-08-03 20:05 UTC, merged

2020-08-03 20:10 UTC, fphammerle commented
thanks! :)